patches: add a few build patches for native gcc 4.7.4
Gcc 4.7 remains substantially faster than its successors and is stlil
a good choice for quick build validations, plus it doesn't spit absurd
fallthrough warnings like gcc-6.5. However with modern toolchains it
fails to build with:

  ./md-unwind-support.h:60:47: error: dereferencing pointer to incomplete type

Also it doesn't enable -fuse-ld=gold in native builds that some modern
projects enable, and which was backported into various much older distro
toolchains. This adds the two required backports to do this.